<?php

/**
 * Base class that represents a row from the 'place' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct  8 18:09:39 2010
 *
 * @package    lib.model.om
 */
abstract class BasePlace extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PlacePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the contact field.
	 * @var        string
	 */
	protected $contact;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * @var        array MealPlace[] Collection to store aggregation of MealPlace objects.
	 */
	protected $collMealPlaces;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMealPlaces.
	 */
	private $lastMealPlaceCriteria = null;

	/**
	 * @var        array Meal[] Collection to store aggregation of Meal objects.
	 */
	protected $collMeals;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMeals.
	 */
	private $lastMealCriteria = null;

	/**
	 * @var        array Item[] Collection to store aggregation of Item objects.
	 */
	protected $collItems;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItems.
	 */
	private $lastItemCriteria = null;

	/**
	 * @var        array Vote[] Collection to store aggregation of Vote objects.
	 */
	protected $collVotes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVotes.
	 */
	private $lastVoteCriteria = null;

	/**
	 * @var        array Suggestion[] Collection to store aggregation of Suggestion objects.
	 */
	protected $collSuggestions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSuggestions.
	 */
	private $lastSuggestionCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PlacePeer';
	
	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [contact] column value.
	 * 
	 * @return     string
	 */
	public function getContact()
	{
		return $this->contact;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Place The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PlacePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Place The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = PlacePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Place The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = PlacePeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [contact] column.
	 * 
	 * @param      string $v new value
	 * @return     Place The current object (for fluent API support)
	 */
	public function setContact($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->contact !== $v) {
			$this->contact = $v;
			$this->modifiedColumns[] = PlacePeer::CONTACT;
		}

		return $this;
	} // setContact()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     Place The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = PlacePeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->description = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->contact = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->image = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = PlacePeer::NUM_COLUMNS - PlacePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Place object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlacePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PlacePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collMealPlaces = null;
			$this->lastMealPlaceCriteria = null;

			$this->collMeals = null;
			$this->lastMealCriteria = null;

			$this->collItems = null;
			$this->lastItemCriteria = null;

			$this->collVotes = null;
			$this->lastVoteCriteria = null;

			$this->collSuggestions = null;
			$this->lastSuggestionCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlacePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePlace:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}
			
			if ($ret) {
				PlacePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePlace:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}
				
				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PlacePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePlace:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePlace:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}
				
				PlacePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PlacePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PlacePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PlacePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collMealPlaces !== null) {
				foreach ($this->collMealPlaces as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMeals !== null) {
				foreach ($this->collMeals as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collItems !== null) {
				foreach ($this->collItems as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collVotes !== null) {
				foreach ($this->collVotes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSuggestions !== null) {
				foreach ($this->collSuggestions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PlacePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collMealPlaces !== null) {
					foreach ($this->collMealPlaces as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMeals !== null) {
					foreach ($this->collMeals as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collItems !== null) {
					foreach ($this->collItems as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collVotes !== null) {
					foreach ($this->collVotes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSuggestions !== null) {
					foreach ($this->collSuggestions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PlacePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getDescription();
				break;
			case 3:
				return $this->getContact();
				break;
			case 4:
				return $this->getImage();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PlacePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getDescription(),
			$keys[3] => $this->getContact(),
			$keys[4] => $this->getImage(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PlacePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setDescription($value);
				break;
			case 3:
				$this->setContact($value);
				break;
			case 4:
				$this->setImage($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PlacePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescription($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setContact($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setImage($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PlacePeer::DATABASE_NAME);

		if ($this->isColumnModified(PlacePeer::ID)) $criteria->add(PlacePeer::ID, $this->id);
		if ($this->isColumnModified(PlacePeer::NAME)) $criteria->add(PlacePeer::NAME, $this->name);
		if ($this->isColumnModified(PlacePeer::DESCRIPTION)) $criteria->add(PlacePeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(PlacePeer::CONTACT)) $criteria->add(PlacePeer::CONTACT, $this->contact);
		if ($this->isColumnModified(PlacePeer::IMAGE)) $criteria->add(PlacePeer::IMAGE, $this->image);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PlacePeer::DATABASE_NAME);

		$criteria->add(PlacePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Place (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setDescription($this->description);

		$copyObj->setContact($this->contact);

		$copyObj->setImage($this->image);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getMealPlaces() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMealPlace($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMeals() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMeal($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getItems() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItem($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getVotes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVote($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSuggestions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSuggestion($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Place Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PlacePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PlacePeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collMealPlaces collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMealPlaces()
	 */
	public function clearMealPlaces()
	{
		$this->collMealPlaces = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMealPlaces collection (array).
	 *
	 * By default this just sets the collMealPlaces collection to an empty array (like clearcollMealPlaces());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMealPlaces()
	{
		$this->collMealPlaces = array();
	}

	/**
	 * Gets an array of MealPlace objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Place has previously been saved, it will retrieve
	 * related MealPlaces from storage. If this Place is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MealPlace[]
	 * @throws     PropelException
	 */
	public function getMealPlaces($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMealPlaces === null) {
			if ($this->isNew()) {
			   $this->collMealPlaces = array();
			} else {

				$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

				MealPlacePeer::addSelectColumns($criteria);
				$this->collMealPlaces = MealPlacePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

				MealPlacePeer::addSelectColumns($criteria);
				if (!isset($this->lastMealPlaceCriteria) || !$this->lastMealPlaceCriteria->equals($criteria)) {
					$this->collMealPlaces = MealPlacePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMealPlaceCriteria = $criteria;
		return $this->collMealPlaces;
	}

	/**
	 * Returns the number of related MealPlace objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MealPlace objects.
	 * @throws     PropelException
	 */
	public function countMealPlaces(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMealPlaces === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

				$count = MealPlacePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

				if (!isset($this->lastMealPlaceCriteria) || !$this->lastMealPlaceCriteria->equals($criteria)) {
					$count = MealPlacePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMealPlaces);
				}
			} else {
				$count = count($this->collMealPlaces);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MealPlace object to this object
	 * through the MealPlace foreign key attribute.
	 *
	 * @param      MealPlace $l MealPlace
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMealPlace(MealPlace $l)
	{
		if ($this->collMealPlaces === null) {
			$this->initMealPlaces();
		}
		if (!in_array($l, $this->collMealPlaces, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMealPlaces, $l);
			$l->setPlace($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Place is new, it will return
	 * an empty collection; or if this Place has previously
	 * been saved, it will retrieve related MealPlaces from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Place.
	 */
	public function getMealPlacesJoinMeal($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMealPlaces === null) {
			if ($this->isNew()) {
				$this->collMealPlaces = array();
			} else {

				$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

				$this->collMealPlaces = MealPlacePeer::doSelectJoinMeal($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MealPlacePeer::PLACE_ID, $this->id);

			if (!isset($this->lastMealPlaceCriteria) || !$this->lastMealPlaceCriteria->equals($criteria)) {
				$this->collMealPlaces = MealPlacePeer::doSelectJoinMeal($criteria, $con, $join_behavior);
			}
		}
		$this->lastMealPlaceCriteria = $criteria;

		return $this->collMealPlaces;
	}

	/**
	 * Clears out the collMeals collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMeals()
	 */
	public function clearMeals()
	{
		$this->collMeals = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMeals collection (array).
	 *
	 * By default this just sets the collMeals collection to an empty array (like clearcollMeals());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMeals()
	{
		$this->collMeals = array();
	}

	/**
	 * Gets an array of Meal objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Place has previously been saved, it will retrieve
	 * related Meals from storage. If this Place is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Meal[]
	 * @throws     PropelException
	 */
	public function getMeals($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMeals === null) {
			if ($this->isNew()) {
			   $this->collMeals = array();
			} else {

				$criteria->add(MealPeer::PLACE_ID, $this->id);

				MealPeer::addSelectColumns($criteria);
				$this->collMeals = MealPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MealPeer::PLACE_ID, $this->id);

				MealPeer::addSelectColumns($criteria);
				if (!isset($this->lastMealCriteria) || !$this->lastMealCriteria->equals($criteria)) {
					$this->collMeals = MealPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMealCriteria = $criteria;
		return $this->collMeals;
	}

	/**
	 * Returns the number of related Meal objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Meal objects.
	 * @throws     PropelException
	 */
	public function countMeals(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMeals === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MealPeer::PLACE_ID, $this->id);

				$count = MealPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MealPeer::PLACE_ID, $this->id);

				if (!isset($this->lastMealCriteria) || !$this->lastMealCriteria->equals($criteria)) {
					$count = MealPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMeals);
				}
			} else {
				$count = count($this->collMeals);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Meal object to this object
	 * through the Meal foreign key attribute.
	 *
	 * @param      Meal $l Meal
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMeal(Meal $l)
	{
		if ($this->collMeals === null) {
			$this->initMeals();
		}
		if (!in_array($l, $this->collMeals, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMeals, $l);
			$l->setPlace($this);
		}
	}

	/**
	 * Clears out the collItems collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItems()
	 */
	public function clearItems()
	{
		$this->collItems = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItems collection (array).
	 *
	 * By default this just sets the collItems collection to an empty array (like clearcollItems());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItems()
	{
		$this->collItems = array();
	}

	/**
	 * Gets an array of Item objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Place has previously been saved, it will retrieve
	 * related Items from storage. If this Place is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Item[]
	 * @throws     PropelException
	 */
	public function getItems($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItems === null) {
			if ($this->isNew()) {
			   $this->collItems = array();
			} else {

				$criteria->add(ItemPeer::PLACE_ID, $this->id);

				ItemPeer::addSelectColumns($criteria);
				$this->collItems = ItemPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ItemPeer::PLACE_ID, $this->id);

				ItemPeer::addSelectColumns($criteria);
				if (!isset($this->lastItemCriteria) || !$this->lastItemCriteria->equals($criteria)) {
					$this->collItems = ItemPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItemCriteria = $criteria;
		return $this->collItems;
	}

	/**
	 * Returns the number of related Item objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Item objects.
	 * @throws     PropelException
	 */
	public function countItems(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItems === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ItemPeer::PLACE_ID, $this->id);

				$count = ItemPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ItemPeer::PLACE_ID, $this->id);

				if (!isset($this->lastItemCriteria) || !$this->lastItemCriteria->equals($criteria)) {
					$count = ItemPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collItems);
				}
			} else {
				$count = count($this->collItems);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Item object to this object
	 * through the Item foreign key attribute.
	 *
	 * @param      Item $l Item
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItem(Item $l)
	{
		if ($this->collItems === null) {
			$this->initItems();
		}
		if (!in_array($l, $this->collItems, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItems, $l);
			$l->setPlace($this);
		}
	}

	/**
	 * Clears out the collVotes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVotes()
	 */
	public function clearVotes()
	{
		$this->collVotes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVotes collection (array).
	 *
	 * By default this just sets the collVotes collection to an empty array (like clearcollVotes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVotes()
	{
		$this->collVotes = array();
	}

	/**
	 * Gets an array of Vote objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Place has previously been saved, it will retrieve
	 * related Votes from storage. If this Place is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Vote[]
	 * @throws     PropelException
	 */
	public function getVotes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVotes === null) {
			if ($this->isNew()) {
			   $this->collVotes = array();
			} else {

				$criteria->add(VotePeer::PLACE_ID, $this->id);

				VotePeer::addSelectColumns($criteria);
				$this->collVotes = VotePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VotePeer::PLACE_ID, $this->id);

				VotePeer::addSelectColumns($criteria);
				if (!isset($this->lastVoteCriteria) || !$this->lastVoteCriteria->equals($criteria)) {
					$this->collVotes = VotePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVoteCriteria = $criteria;
		return $this->collVotes;
	}

	/**
	 * Returns the number of related Vote objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Vote objects.
	 * @throws     PropelException
	 */
	public function countVotes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVotes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VotePeer::PLACE_ID, $this->id);

				$count = VotePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VotePeer::PLACE_ID, $this->id);

				if (!isset($this->lastVoteCriteria) || !$this->lastVoteCriteria->equals($criteria)) {
					$count = VotePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVotes);
				}
			} else {
				$count = count($this->collVotes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Vote object to this object
	 * through the Vote foreign key attribute.
	 *
	 * @param      Vote $l Vote
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVote(Vote $l)
	{
		if ($this->collVotes === null) {
			$this->initVotes();
		}
		if (!in_array($l, $this->collVotes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVotes, $l);
			$l->setPlace($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Place is new, it will return
	 * an empty collection; or if this Place has previously
	 * been saved, it will retrieve related Votes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Place.
	 */
	public function getVotesJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVotes === null) {
			if ($this->isNew()) {
				$this->collVotes = array();
			} else {

				$criteria->add(VotePeer::PLACE_ID, $this->id);

				$this->collVotes = VotePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VotePeer::PLACE_ID, $this->id);

			if (!isset($this->lastVoteCriteria) || !$this->lastVoteCriteria->equals($criteria)) {
				$this->collVotes = VotePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastVoteCriteria = $criteria;

		return $this->collVotes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Place is new, it will return
	 * an empty collection; or if this Place has previously
	 * been saved, it will retrieve related Votes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Place.
	 */
	public function getVotesJoinMeal($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVotes === null) {
			if ($this->isNew()) {
				$this->collVotes = array();
			} else {

				$criteria->add(VotePeer::PLACE_ID, $this->id);

				$this->collVotes = VotePeer::doSelectJoinMeal($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VotePeer::PLACE_ID, $this->id);

			if (!isset($this->lastVoteCriteria) || !$this->lastVoteCriteria->equals($criteria)) {
				$this->collVotes = VotePeer::doSelectJoinMeal($criteria, $con, $join_behavior);
			}
		}
		$this->lastVoteCriteria = $criteria;

		return $this->collVotes;
	}

	/**
	 * Clears out the collSuggestions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSuggestions()
	 */
	public function clearSuggestions()
	{
		$this->collSuggestions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSuggestions collection (array).
	 *
	 * By default this just sets the collSuggestions collection to an empty array (like clearcollSuggestions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSuggestions()
	{
		$this->collSuggestions = array();
	}

	/**
	 * Gets an array of Suggestion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Place has previously been saved, it will retrieve
	 * related Suggestions from storage. If this Place is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Suggestion[]
	 * @throws     PropelException
	 */
	public function getSuggestions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSuggestions === null) {
			if ($this->isNew()) {
			   $this->collSuggestions = array();
			} else {

				$criteria->add(SuggestionPeer::PLACE_ID, $this->id);

				SuggestionPeer::addSelectColumns($criteria);
				$this->collSuggestions = SuggestionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SuggestionPeer::PLACE_ID, $this->id);

				SuggestionPeer::addSelectColumns($criteria);
				if (!isset($this->lastSuggestionCriteria) || !$this->lastSuggestionCriteria->equals($criteria)) {
					$this->collSuggestions = SuggestionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSuggestionCriteria = $criteria;
		return $this->collSuggestions;
	}

	/**
	 * Returns the number of related Suggestion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Suggestion objects.
	 * @throws     PropelException
	 */
	public function countSuggestions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PlacePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSuggestions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SuggestionPeer::PLACE_ID, $this->id);

				$count = SuggestionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SuggestionPeer::PLACE_ID, $this->id);

				if (!isset($this->lastSuggestionCriteria) || !$this->lastSuggestionCriteria->equals($criteria)) {
					$count = SuggestionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSuggestions);
				}
			} else {
				$count = count($this->collSuggestions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Suggestion object to this object
	 * through the Suggestion foreign key attribute.
	 *
	 * @param      Suggestion $l Suggestion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSuggestion(Suggestion $l)
	{
		if ($this->collSuggestions === null) {
			$this->initSuggestions();
		}
		if (!in_array($l, $this->collSuggestions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSuggestions, $l);
			$l->setPlace($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collMealPlaces) {
				foreach ((array) $this->collMealPlaces as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMeals) {
				foreach ((array) $this->collMeals as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collItems) {
				foreach ((array) $this->collItems as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collVotes) {
				foreach ((array) $this->collVotes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSuggestions) {
				foreach ((array) $this->collSuggestions as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collMealPlaces = null;
		$this->collMeals = null;
		$this->collItems = null;
		$this->collVotes = null;
		$this->collSuggestions = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePlace:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePlace::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}
	
} // BasePlace
