# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: user, action: index }

# generic rules
# please, remove them by adding more specific rules
register:
  url:   /register
  param: { module: sfGuardAuth, action: register }

registered:
  url:   /registered
  param: { module: sfGuardAuth, action: registered }
  
openid_signin:
  url:   /openidAuth/signin
  param: { module: openidAuth, action: signin }
  
openid_finishauth:
  url:   /openidAuth/finish
  param: { module: openidAuth, action: finish }
  
openid_error:
  url:   /openidAuth/openidError
  param: { module: openidAuth, action: openidError }

places:
  url:   /places
  param: { module: place, action: index }

show_place:
  url:   /place/:place_id
  param: { module: place, action: show }

view_orders:
  url:   /orders/:meal_id/:layout
  param: { module: meal, action: viewOrders, layout: html }

view_votes:
  url:   /votes/:meal_id
  param: { module: meal, action: viewVotes }
  
stop_vote:
  url:   /stopVotes/:meal_id/:from
  param: { module: meal, action: stopVotes, meal_id: 0, from: meals }

stop_order:
  url:   /stopOrders/:meal_id/:from
  param: { module: meal, action: stopOrders, meal_id: 0, from: meals }

start_vote:
  url:   /startVotes/:meal_id
  param: { module: meal, action: startVotes }

start_order:
  url:   /startOrders/:meal_id
  param: { module: meal, action: startOrders }
  
vote:
  url:   /vote/:meal_id/:from
  param: { module: meal, action: vote, meal_id: 0, from: meals }
  
meals:
  url:   /meals/:week
  param: { module: meal, action: index, week: 0 }

order:
  url:   /order/:meal_id/:from/:prev_meal
  param: { module: meal, action: order, meal_id: 0, from: meals, prev_meal: false }
  
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }