generator:
  class: sfPropelGenerator
  param:
    model_class:           place
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              place
    plural:                places
    route_prefix:          place
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: List of Places
        object_actions:
          _edit:        ~
          _delete:      ~
        batch_actions:
          _delete: ~
        actions:
          _new: ~
        sort:  id
        display: [name, description, contact]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
