<?php


/**
 * Skeleton subclass for performing query and update operations on the 'meal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MealPeer extends BaseMealPeer {
    
    public static function getMealPlaceId($meal_id) {
        $c = new Criteria();
        $c->add(self::ID, $meal_id, Criteria::EQUAL);
        $meal = self::doSelectOne($c);
        return $meal->getPlaceId();
    }
    
} // MealPeer
