<?php


/**
 * Skeleton subclass for representing a row from the 'meal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Meal extends BaseMeal
{
    
    public function userHasVoted($user_id) {
        $vote = VotePeer::getVote($this->getId(), $user_id);
        if(!empty($vote)) {
            return true;
        }
        return false;
    }
    
    public function isVotingStopped() {
        if(1 == $this->getVotingStopped()) {
            return true;
        }
        return false;
    }
    
    public function isOrderingStopped() {
        if(1 == $this->getOrderingStopped()) {
            return true;
        }
        return false;
    }
    
    public function getVoteCount() {
        $c = new Criteria();
        $c->add(VotePeer::MEAL_ID, $this->getId());
        $vote_count = VotePeer::doCount($c);
        return $vote_count;
    }
    
} // Meal