<?php


/**
 * Skeleton subclass for representing a row from the 'meal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Meal extends BaseMeal
{
    
    public function userHasVoted($user_id) {
        return VotePeer::checkIfUserHasVoted($this->getId(), $user_id);
    }
    
} // Meal
