<?php


/**
 * Skeleton subclass for performing query and update operations on the 'meal_order' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 09:03:55 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MealOrderPeer extends BaseMealOrderPeer
{
    
    public static function getOrder($meal_id, $user_id) {
        $c = new Criteria();
        $c->add(self::MEAL_ID, $meal_id, Criteria::EQUAL);
        $c->add(self::SF_GUARD_USER_ID, $user_id, Criteria::EQUAL);
        $order = self::doSelectOne($c);
        return $order;
    }
    
    public static function getOrderCount($meal_id) {
        $c = new Criteria();
        $c->add(self::MEAL_ID, $meal_id);
        $order_count = self::doCount($c);
        return $order_count;
    }

} // MealOrderPeer
