<?php


/**
 * Skeleton subclass for performing query and update operations on the 'meal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MealPeer extends BaseMealPeer {
    
    public static function getMeal($meal_id) {
        $c = new Criteria();
        $c->add(self::ID, $meal_id, Criteria::EQUAL);
        $meal = self::doSelectOne($c);
        return $meal;
    }
    
    public static function getMealPlaceId($meal_id) {
        $meal = self::getMeal($meal_id);
        return $meal->getPlaceId();
    }
    
    public static function getScheduledMeal() {
        $c = new Criteria();
        $c->add(self::SCHEDULED_AT, date('Y-m-d H:i:s'), Criteria::GREATER_EQUAL);
        $c->addAscendingOrderByColumn(self::SCHEDULED_AT);
        $meal = self::doSelectOne($c);
        return $meal;
    }
     
    public static function getMealsByWeek($sunday, $saturday = null) {
        $c = new Criteria();
        $c->add(self::SCHEDULED_AT, $saturday . ' 23:59:59', Criteria::LESS_EQUAL);
        $c->addAnd(self::SCHEDULED_AT, $sunday . ' 00:00:00', Criteria::GREATER_EQUAL);
        $c->addAscendingOrderByColumn(self::SCHEDULED_AT);
        $meals = self::doSelect($c);
        return $meals;
    }
    
} // MealPeer
