<?php


/**
 * Skeleton subclass for performing query and update operations on the 'meal_place' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Oct  7 03:08:34 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MealPlacePeer extends BaseMealPlacePeer {

} // MealPlacePeer
