<?php


/**
 * Skeleton subclass for performing query and update operations on the 'menu' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MenuPeer extends BaseMenuPeer {

    public static function getPlaceMenu($place_id) {
        $c = new Criteria();
        $c->addJoin(self::ID, ItemPeer::MENU_ID);
        $c->add(self::PLACE_ID, $place_id, Criteria::EQUAL);
        $menu = self::doSelectOne($c);
        return $menu;
    }

} // MenuPeer
