<?php


/**
 * Skeleton subclass for representing a row from the 'place' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep  8 08:38:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Place extends BasePlace {
    
    public function __toString() {
        return $this->getName();
    }
    
} // Place
