<?php


/**
 * Skeleton subclass for performing query and update operations on the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep  6 11:09:06 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UserPeer extends BaseUserPeer
{
    public static function checkUser($username, $password) {
        $password = sha1($password . sfConfig::get('app_salt_string'));
        $c = new Criteria();
        $c->add(self::USERNAME, $username, Criteria::EQUAL);
        $c->add(self::PASSWORD, $password, Criteria::EQUAL);
        $user = self::doSelectOne($c);
        if(!empty($user)) {
            return true;
        }
        return false;
    }
} // UserPeer
