<?php


/**
 * Skeleton subclass for performing query and update operations on the 'vote' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Sep 11 05:14:18 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VotePeer extends BaseVotePeer
{

    public static function checkIfUserHasVoted($meal_id, $user_id) {
        $vote = self::getVote($meal_id, $user_id);
        if(!empty($vote)) {
            return true;
        }
        return false;
    }
    
    public static function getVote($meal_id, $user_id) {
        $c = new Criteria();
        $c->add(self::MEAL_ID, $meal_id, Criteria::EQUAL);
        $c->add(self::SF_GUARD_USER_ID, $user_id, Criteria::EQUAL);
        $vote = self::doSelectOne($c);
        return $vote;
    }
    
} // VotePeer
