<?php


/**
 * Skeleton subclass for performing query and update operations on the 'vote' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Sep 11 05:14:18 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VotePeer extends BaseVotePeer {

} // VotePeer
