propel:
  meal_order:
    id:               ~
    meal_id:          { type: integer, foreignTable: meal, foreignReference: id, required: true, onDelete: cascade }
    item_id:          { type: integer, foreignTable: item, foreignReference: id, required: true, onDelete: cascade }
    sf_guard_user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    created_at:       ~
    updated_at:       ~
  meal:
    id:               ~
    place_id:         { type: integer, foreignTable: place, foreignReference: id, onDelete: cascade }
    type:             { type: varchar(9), required: true }
    voting_stopped:   { type: tinyint, default: 0 }
    ordering_stopped: { type: tinyint, default: 0 }
    schedule_at:      { type: timestamp, required: true }
    created_at:       ~
    updated_at:       ~
  item:
    id:               ~
    place_id:         { type: integer, foreignTable: place, foreignReference: id, required: true, onDelete: cascade }
    name:             { type: varchar(150), required: true }
    description:      { type: longvarchar }
    price:            { type: float, required: true }
  place:
    id:               ~
    name:             { type: varchar(150), required: true }
    description:      { type: longvarchar }
    contact:          { type: varchar(15) }
  vote:
    id:               ~
    place_id:         { type: integer, foreignTable: place, foreignReference: id, required: true, onDelete: cascade }
    sf_guard_user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    meal_id:          { type: integer, foreignTable: meal, foreignReference: id, required: true, onDelete: cascade }
    created_at:       ~
    updated_at:       ~
  sf_guard_user_profile:
    _attributes:     { phpName: sfGuardUserProfile }
    id:
    user_id:         { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    first_name:      varchar(20)
    last_name:       varchar(20)
    birthday:        date