generator:
  class: sfPropelGenerator
  param:
    model_class:           meal
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              meal
    plural:                meals
    route_prefix:          meal
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: List of Meals
        object_actions:
          _edit:        ~
          _delete:      ~
        batch_actions:
          _delete: ~
        actions:
          _new: ~
        sort:  id
        display: [_place, type, voting_stopped, ordering_stopped]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
