generator:
  class: sfPropelGenerator
  param:
    model_class:           item
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              item
    plural:                items
    route_prefix:          item
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: List of Items
        object_actions:
          _edit:        ~
          _delete:      ~
        batch_actions:
          _delete: ~
        actions:
          _new: ~
        sort:  id
        display: [_place, name, description, price]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
